### PR TITLE
Update url for google maps, and ability to specify lat/lon position

### PR DESCRIPTION
**Pull request by chris-j-major**

### CODE REVIEW

**Comment by kmoe** [comment]
Wow, thanks for the super fast PR!

I've made a lot of progress this evening on my local machine, but I'll merge this as soon as I've pushed my latest changes.

**Comment by chris-j-major** [comment]
The url isn't working yet, so don't make any effort to get the pr in

**Comment by chris-j-major** [comment]
Just got the urls working, should now giving walking directions :)

**Comment by kmoe** [comment]
Thanks! LGTM with a rebase.

**Pull request closed without merging**
